name:               "Zikang Xiong"
description:        "PhD student @ Purdue CS"

url:                "https://www.cs.purdue.edu/homes/xiong84/"
author:             "ZikangXiong"
email:              "zikangxiong@gmail.com"
gravatar_hash:      "cf4dc3620a0f6c636ce921cd8a69f6ab"
twitter:            "caffe_tt"
email:              "zikangxiong@gmail.com"
github:             "ZikangXiong"
# pinterest:          "jhondoe"
linkedin:           "zikang-xiong-934a05138"
# facebook:           "jhondoe"

disqus_shortname:   ""

background:         "http://apple.wallpapersfine.com/wallpapers/original/1242x2208/w-5273.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Research"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
