name:               "Quan Wang"
description:        "MSEC @ Duke CS + Econ | Aspiring Software Engineer"

url:                "https://cv.quanwang.website/"
author:             "QuanWang"
email:              "quan.wang@duke.edu"
gravatar_hash:      "a0034accdfff21f5e5d232fcb58e74fc"
twitter:            "QuanWan84655635"
email:              "quan.wang@duke.edu"
github:             "Mushroom-Wang"
linkedin:           "quan-wang"
# google-scholar:     "H-EoAgYAAAAJ"
# google-analytics:   "G-QV8CL0LPN5"

background:         "https://user-images.githubusercontent.com/73256697/111019101-17ec7f80-838b-11eb-8de3-ff104e11481e.jpg"
favicon:            true # generate with https://realfavicongenerator.net/, and place all the icons under resoureces/

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         "/about"
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate


# disqus_shortname:   "zikangxiong"
# facebook:           "jhondoe"
# pinterest:          "jhondoe"

# nav:
#   - name:           "About"
#     href:           "/about"
#   - name:           "Research"
#     href:           "/releases"
