name:               "Zikang Xiong"
description:        "PhD student @ Purdue CS"

url:                "https://www.cs.purdue.edu/homes/xiong84/"
author:             "ZikangXiong"
email:              "zikangxiong@gmail.com"
gravatar_hash:      "cf4dc3620a0f6c636ce921cd8a69f6ab"
twitter:            "caffe_tt"
email:              "zikangxiong@gmail.com"
github:             "ZikangXiong"
linkedin:           "zikang-xiong-934a05138"
google-scholar:     "H-EoAgYAAAAJ"
google-analytics:   "G-XKP43V9XVL"

background:         "https://user-images.githubusercontent.com/73256697/111019101-17ec7f80-838b-11eb-8de3-ff104e11481e.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         "/about"
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate


# disqus_shortname:   "zikangxiong"
# facebook:           "jhondoe"
# pinterest:          "jhondoe"

# nav:
#   - name:           "About"
#     href:           "/about"
#   - name:           "Research"
#     href:           "/releases"
